spring.application.name=CarRev

# MongoDB
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=carrev
spring.data.mongodb.auto-index-creation=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32_CHARS_MIN
jwt.access.expiration=900
jwt.refresh.expiration=2592000

