spring.application.name=CarRev

# MongoDB
#spring.mongodb.host=10.1.1.89
spring.data.mongodb.uri=mongodb://10.1.1.88:27017,10.1.1.89:27017,10.1.1.90:27017/carrev?replicaSet=rs0
#spring.mongodb.port=27017
spring.mongodb.database=carrev
spring.data.mongodb.auto-index-creation=true

# Redis
spring.data.redis.host=10.1.1.89
spring.data.redis.port=6379
carsearch.count-cache-ttl-seconds=60

#change this for proper schedule
car.sales.recompute-cron=0 0 0 * * MON
car.analytics.cron=0 59 23 * * *

jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32_CHARS_MIN
jwt.access.expiration=900
jwt.refresh.expiration=2592000

logging.level.org.springframework.security=DEBUG
#SpringDoc configuration
springdoc.swagger-ui.on-complete=ui => { window.ui = ui; }
springdoc.swagger-ui.additional-config-url=/swagger-auth.js

#neo4j
spring.neo4j.uri=bolt://10.1.1.87:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4jneo4j
