version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: carrev-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: carrev
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: carrev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
